<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_GdprCookie
 */
?>
<?php
/** @var \Amasty\GdprCookie\Block\CookieBar $block */
/** @var \Magento\Framework\Escaper $escaper */

$notificationText = /** @noEscape */ $block->getNotificationText();
$confirmationModal = \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION_MODAL;
$confirmationPopup = \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION_POPUP;
$confirmationClassic = \Amasty\GdprCookie\Model\Config\Source\CookiePolicyBarStyle::CONFIRMATION;
?>
<script>
    window.isGdprCookieEnabled = true;
</script>
<?php if ($block->getNoticeType() === $confirmationModal && $notificationText): ?>

    <div data-role="gdpr-cookie-container" class="amgdprcookie-modal-template" data-bind="scope: 'gdpr-cookie-modal'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- ko if: $data.elems().length -->
            <!-- ko foreach: $data.elems() -->
                <!--ko template: getTemplate()--><!-- /ko -->
            <!-- /ko -->
        <!-- /ko -->
    </div>
    <div class="amgdprcookie-modal-block" data-amgdpr-js="modal"></div>
    <script type="text/x-magento-init">
    {
        "[data-role=gdpr-cookie-container]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "gdpr-cookie-modal": {
                        "component": "Amasty_GdprCookie/js/modal",
                        "isNotice": <?= $escaper->escapeHtmlAttr($block->isNotice()) ?>,
                        "cookieText": <?= /** @noEscape */ $notificationText ?>,
                        "websiteInteraction": "<?= $escaper->escapeHtmlAttr($block->getWebsiteInteraction()) ?>",
                        "firstShowProcess": "<?= $escaper->escapeHtmlAttr($block->isProcessFirstShow()) ?>",
                        "acceptBtnText": "<?= $escaper->escapeHtml($block->getAcceptButtonName()) ?>",
                        "settingsBtnText": "<?= $escaper->escapeHtml($block->getSettingsButtonName()) ?>"
                    }
                }
            }
        }
    }
    </script>
<?php elseif (($block->getNoticeType() === $confirmationClassic ||
        $block->getNoticeType() === $confirmationPopup) && $notificationText): ?>
    <!-- ko scope: 'gdpr-cookie-container' -->
    <div data-role="gdpr-cookie-container" class="amgdprcookie-bar-template" data-bind="css: {'-bottom' : isScrollBottom, '-popup' : isPopup}">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <!-- /ko -->
    <script type="text/x-magento-init">
    {
        "[data-role=gdpr-cookie-container]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "gdpr-cookie-container": {
                        "component": "Amasty_GdprCookie/js/cookies",
                        "isNotice": <?= $escaper->escapeHtmlAttr($block->isNotice()) ?>,
                        "policyText": <?= /** @noEscape */ $notificationText ?>,
                        "allowLink": "<?= $escaper->escapeUrl($block->getAllowLink()) ?>",
                        "websiteInteraction": "<?= $escaper->escapeHtmlAttr($block->getWebsiteInteraction()) ?>",
                        "firstShowProcess": "<?= $escaper->escapeHtmlAttr($block->isProcessFirstShow()) ?>",
                        "barLocation": "<?= $escaper->escapeHtmlAttr($block->getBarLocation()) ?>",
                        "isPopup": <?= /* @noEscape */ (int)($block->getNoticeType() === $confirmationPopup) ?>,
                        "acceptBtnText": "<?= $escaper->escapeHtml($block->getAcceptButtonName()) ?>",
                        "settingsBtnText": "<?= $escaper->escapeHtml($block->getSettingsButtonName()) ?>"
                    }
                }
            }
        }
    }
    </script>
    <style>
        .amgdprcookie-bar-template {
                z-index: 15;
            <?php if ((int)$block->getBarLocation()): ?>
                top: 0;
            <?php else: ?>
                bottom: 0;
            <?php endif; ?>
        }
    </style>
<?php endif; ?>
<?php if ($notificationText): ?>
<style>
    .amgdprcookie-modal-template,
    .amgdprcookie-bar-container {
    <?php if ((int)$block->getBarLocation() === \Amasty\GdprCookie\Model\Config\Source\CookieBarLocation::DISPLAY_AT_FOOTER): ?>
        bottom: unset;
    <?php endif; ?>
        background-color: <?= $escaper->escapeHtml($block->getBackgroundColor()); ?>;
    }
    .amgdprcookie-modal-template .amgdprcookie-policy,
    .amgdprcookie-bar-container .amgdprcookie-policy {
        color: <?= $escaper->escapeHtml($block->getPolicyTextColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-text,
    .amgdprcookie-bar-container .amgdprcookie-text {
        color: <?= $escaper->escapeHtml($block->getDescriptionTextColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-header,
    .amgdprcookie-bar-container .amgdprcookie-header {
        color: <?= $escaper->escapeHtml($block->getTitleTextColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-link,
    .amgdprcookie-modal-template .amgdprcookie-policy a,
    .amgdprcookie-bar-container .amgdprcookie-policy a {
        color: <?= $escaper->escapeHtml($block->getLinksColor()); ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-save,
    .amgdprcookie-bar-container .amgdprcookie-button.-allow {
        background-color: <?= $escaper->escapeHtml($block->getAcceptButtonColor()) ?>;
        border-color: <?= $escaper->escapeHtml($block->getAcceptButtonColor()) ?>;
        color: <?= $escaper->escapeHtml($block->getAcceptTextColor()) ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-save:hover,
    .amgdprcookie-bar-container .amgdprcookie-button.-allow:hover {
        background-color: <?= $escaper->escapeHtml($block->getAcceptButtonColorHover()) ?>;
        border-color: <?= $escaper->escapeHtml($block->getAcceptButtonColorHover()) ?>;
        color: <?= $escaper->escapeHtml($block->getAcceptTextColorHover()) ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-allow,
    .amgdprcookie-bar-container .amgdprcookie-button.-settings {
        background-color: <?= $escaper->escapeHtml($block->getSettingsButtonColor()) ?>;
        border-color: <?= $escaper->escapeHtml($block->getSettingsButtonColor()) ?>;
        color: <?= $escaper->escapeHtml($block->getSettingsTextColor()) ?>;
    }

    .amgdprcookie-modal-template .amgdprcookie-button.-allow:hover,
    .amgdprcookie-bar-container .amgdprcookie-button.-settings:hover {
        background-color: <?= $escaper->escapeHtml($block->getSettingsButtonColorHover()) ?>;
        border-color: <?= $escaper->escapeHtml($block->getSettingsButtonColorHover()) ?>;
        color: <?= $escaper->escapeHtml($block->getSettingsTextColorHover()) ?>;
    }
</style>
<?php endif; ?>
