<?php
$porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
?>
<li><a href="<?php echo $porto_helper->getBaseLinkUrl(); ?>about-us"><?php echo __('About Us'); ?></a></li>
<li><a href="<?php echo $porto_helper->getBaseLinkUrl(); ?>blog"><?php echo __('Blog'); ?></a></li>
<li><a href="<?php echo $porto_helper->getBaseLinkUrl(); ?>contact"><?php echo __('Contact Us'); ?></a></li>

<li class="pre-social-icons bold">
    <a href="https://www.facebook.com"><i class="porto-icon-facebook hidden-xs"></i></a>
</li>
<li class="pre-social-icons bold">
    <a href="https://www.instagram.com"><em class="porto-icon-instagram hidden-xs"></em></a>
</li>
<li class="pre-social-icons bold">
    <a href="https://www.twitter.com"><em class="porto-icon-twitter hidden-xs"></em></a>
</li>
